### ISSUE TITLE
Make PyYaml using the CLoader via libyaml

### ISSUE THREAD

**Issue by Trilarion** [Trilarion/imperialism-remake#15]
This is probably a Windows only problem. PyYaml will use the CLoader if it finds libyaml. However, at least the conda package does not include libyaml. So how to include it? How to include it with packaging with pynsist?

Reason: Using the CLoader is much faster

**Comment by amtyurin** [comment]
Not relevant anymore due to using pickle/python configs instead of Yaml

**Comment by Trilarion** [comment]
True.
